import {
  addJobEvent,
  claimJob,
  countRunningJobs,
  finishJob,
  type GenerationJob,
  getJob,
  listJobs,
  recoverStaleJobs,
  updateJobProgress,
} from "../db/jobs.ts";
import { getModel, touchModelLastUsed } from "../db/models.ts";
import { createAsset, createAssetVersion, getAssetById } from "../db/assets.ts";
import { setPanelPreview } from "../db/storyboards.ts";
import { setShotGenerated } from "../db/scenes.ts";
import { getContentStore } from "../storage/content_store.ts";
import { CancelledError, getAdapter, randomSeed } from "./adapters.ts";

export interface JobRunnerOptions {
  pollMs?: number;
  leaseSeconds?: number;
  gpuConcurrency?: number;
  cpuConcurrency?: number;
}

export interface JobRunner {
  readonly owner: string;
  stop(): Promise<void>;
}

const IMAGE_TASKS = ["text_to_image", "image_to_image"];

function randomHex(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(4));
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * In-process job runner (GEN-003/016/017): polls the queue, claims jobs with
 * leases, executes them through the model adapter, and stores candidates as
 * asset versions with full provenance.
 */
export function startJobRunner(options: JobRunnerOptions = {}): JobRunner {
  const pollMs = options.pollMs ?? 250;
  const leaseSeconds = options.leaseSeconds ?? 60;
  const gpuConcurrency = options.gpuConcurrency ?? 1;
  const cpuConcurrency = options.cpuConcurrency ?? 2;
  const owner = `runner-${randomHex()}`;

  let stopping = false;
  let timer: ReturnType<typeof setTimeout> | undefined;
  const executing = new Set<Promise<void>>();

  async function storeCandidate(
    job: GenerationJob,
    targetAssetId: string,
    userId: number,
    candidate: { content: Uint8Array; extension: string; mime_type: string },
    index: number,
    count: number,
    seedUsed: string,
  ): Promise<string> {
    const model = getModel(job.model_id);
    const store = getContentStore();
    await Deno.mkdir(store.layout.cache, { recursive: true });
    const tempPath = `${store.layout.cache}/.jobgen-${job.id}-${index}`;
    try {
      await Deno.writeFile(tempPath, candidate.content);
      const stored = await store.put(
        tempPath,
        `gen-${job.id.slice(0, 8)}-${index}.${candidate.extension}`,
      );

      const version = createAssetVersion(targetAssetId, userId, {
        content_hash: stored.hash,
        file_path: stored.path,
        format: candidate.extension,
        mime_type: candidate.mime_type,
        file_size: stored.size,
        // The last stored candidate becomes the active version.
        make_active: index === count - 1,
        technical_metadata_json: JSON.stringify({
          job_id: job.id,
          job_type: job.job_type,
          model_id: model?.id,
          model_name: model?.name,
          model_version: model?.version,
          backend: model?.backend,
          prompt_text: job.prompt_text,
          negative_prompt: job.negative_prompt,
          seed_used: seedUsed,
          settings: job.settings,
          input_asset_versions: job.input_asset_versions,
          request: {
            project_id: job.project_id,
            scene_id: job.scene_id,
            shot_id: job.shot_id,
            storyboard_panel_id: job.storyboard_panel_id,
            prompt_version_id: job.prompt_version_id,
          },
          candidate_index: index,
          candidate_count: count,
          generated_at: new Date().toISOString(),
        }),
        notes: `Generated by job ${job.id}`,
      });
      return version.id;
    } finally {
      await Deno.remove(tempPath).catch(() => {});
    }
  }

  /** Run one claimed job to a terminal state. */
  async function executeJob(job: GenerationJob): Promise<void> {
    const jobId = job.id;
    const userId = job.created_by_user_id ?? 0;
    try {
      const model = getModel(job.model_id);
      if (!model) {
        throw new Error(`Model ${job.model_id} no longer exists`);
      }
      touchModelLastUsed(model.id);

      const adapter = getAdapter(model.backend);
      if (!adapter) {
        throw new Error(
          `No adapter registered for backend '${model.backend}' yet (GEN-007)`,
        );
      }

      const seed = job.seed && job.seed !== "random" ? job.seed : randomSeed();
      const hooks = {
        onProgress(progress: number, message: string | null): void {
          updateJobProgress(jobId, progress);
          addJobEvent(jobId, "progress", message, { progress });
        },
        isCancelled(): boolean {
          return getJob(jobId)?.status === "cancelling";
        },
      };

      const result = await adapter.generate(
        {
          jobType: job.job_type,
          seed,
          settings: job.settings,
          inputs: job.input_asset_versions,
          promptText: job.prompt_text,
        },
        hooks,
      );

      let targetAssetId = job.asset_id;
      if (!targetAssetId) {
        const assetType = IMAGE_TASKS.includes(job.job_type)
          ? "image"
          : job.job_type.includes("video")
          ? "video"
          : "audio";
        const asset = createAsset(
          {
            unique_slug: `gen_${randomHex()}`,
            display_name: `Generation ${jobId.slice(0, 8)}`,
            asset_type: assetType,
            library_scope: "global",
          },
          userId,
        );
        targetAssetId = asset.id;
        addJobEvent(jobId, "asset.created", "Created asset for candidates", {
          asset_id: asset.id,
        });
      } else if (getAssetById(targetAssetId)?.status === "deleted") {
        throw new Error("Target asset has been deleted");
      }

      const versionIds: string[] = [];
      for (let i = 0; i < result.candidates.length; i++) {
        if (hooks.isCancelled()) throw new CancelledError();
        const versionId = await storeCandidate(
          job,
          targetAssetId,
          userId,
          result.candidates[i],
          i,
          result.candidates.length,
          result.seedUsed,
        );
        versionIds.push(versionId);
        addJobEvent(jobId, "candidate.created", `Candidate ${i} stored`, {
          asset_id: targetAssetId,
          version_id: versionId,
        });
      }

      // Link the first output back to the creative object that requested it.
      if (versionIds.length > 0) {
        if (job.storyboard_panel_id) {
          setPanelPreview(job.storyboard_panel_id, versionIds[0]);
          addJobEvent(jobId, "panel.linked", "Panel preview linked", {
            version_id: versionIds[0],
          });
        }
        if (job.shot_id) {
          setShotGenerated(job.shot_id, versionIds[0]);
          addJobEvent(jobId, "shot.linked", "Shot output linked", {
            version_id: versionIds[0],
          });
        }
      }

      finishJob(jobId, "succeeded", {
        outputAssetVersionId: versionIds[0] ?? undefined,
        candidateCount: versionIds.length,
        candidateVersionIds: versionIds,
        progress: 100,
      });
    } catch (err) {
      if (err instanceof CancelledError) {
        finishJob(jobId, "cancelled");
        return;
      }
      const message = err instanceof Error ? err.message : String(err);
      finishJob(jobId, "failed", { errorText: message });
    }
  }

  function tick(): void {
    if (stopping) return;
    recoverStaleJobs();

    for (;;) {
      const next = listJobs({ status: "queued", limit: 1 })[0];
      if (!next) break;
      const model = getModel(next.model_id);
      const isGpu = model ? model.backend !== "mock" : false;
      const running = countRunningJobs();
      if (
        isGpu ? running.gpu >= gpuConcurrency : running.cpu >= cpuConcurrency
      ) {
        break;
      }
      const claimed = claimJob(owner, leaseSeconds);
      if (!claimed) break;
      addJobEvent(claimed.id, "claimed", "Job claimed by runner", { owner });
      const p = executeJob(claimed).finally(() => executing.delete(p));
      executing.add(p);
    }
  }

  function armTimer(): void {
    timer = setTimeout(() => {
      tick();
      armTimer();
    }, pollMs);
    Deno.unrefTimer(timer); // never keep the process alive on our own
  }

  // Recover jobs left running by a previous process, then start polling.
  recoverStaleJobs();
  armTimer();

  return {
    owner,
    async stop(): Promise<void> {
      stopping = true;
      if (timer !== undefined) clearTimeout(timer);
      await Promise.allSettled([...executing]);
    },
  };
}
