import { join } from "@std/path";
import { loadConfig } from "../config.ts";
import type { StorageLayout } from "../storage/paths.ts";
import { storageLayout } from "../storage/paths.ts";
import { sha256File } from "../storage/checksums.ts";
import { getModel, type Model, setModelInstalled } from "../db/models.ts";
import { badRequest, conflict, notFound } from "../errors.ts";

// Installed artifacts live at <app_data>/models/<model_id>/model.bin.
export function modelDir(layout: StorageLayout, modelId: string): string {
  return join(layout.models, safeModelId(modelId));
}

export function modelFile(layout: StorageLayout, modelId: string): string {
  return join(modelDir(layout, modelId), "model.bin");
}

function safeModelId(modelId: string): string {
  // Model ids are UUIDs generated by the server, but never trust a raw path.
  if (!/^[a-zA-Z0-9_-]+$/.test(modelId)) {
    throw badRequest("Invalid model id");
  }
  return modelId;
}

export async function fileExists(path: string): Promise<boolean> {
  try {
    return (await Deno.stat(path)).isFile;
  } catch {
    return false;
  }
}

export interface InstallResult {
  fileHash: string;
  fileBytes: number;
}

/** Copy a local source file into the model store (MOD-003). */
export async function installFromLocal(
  layout: StorageLayout,
  modelId: string,
  sourcePath: string,
): Promise<InstallResult> {
  let stat: Deno.FileInfo;
  try {
    stat = await Deno.stat(sourcePath);
  } catch {
    throw badRequest(`Source file does not exist: ${sourcePath}`, "source_path");
  }
  if (!stat.isFile) {
    throw badRequest(`Source path is not a file: ${sourcePath}`, "source_path");
  }

  const target = modelFile(layout, modelId);
  await Deno.mkdir(modelDir(layout, modelId), { recursive: true });
  await Deno.copyFile(sourcePath, target);
  const fileHash = await sha256File(target);
  return { fileHash, fileBytes: stat.size };
}

/**
 * Download a model file into the store (MOD-003, network). Streams to a
 * temp file and renames it into place, so arbitrarily large downloads are
 * bounded only by disk space and a failed download never leaves a partial
 * `model.bin` behind. `maxBytes` of 0 means no limit.
 */
export async function installFromUrl(
  layout: StorageLayout,
  modelId: string,
  url: string,
  maxBytes: number,
): Promise<InstallResult> {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    throw badRequest("repository_url is not a valid URL", "repository_url");
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw badRequest("repository_url must use http or https", "repository_url");
  }

  const res = await fetch(parsed);
  if (!res.ok) {
    throw conflict(`Download failed: HTTP ${res.status}`, "repository_url");
  }
  const contentLength = Number(res.headers.get("Content-Length") ?? "0");
  if (maxBytes > 0 && contentLength > maxBytes) {
    throw badRequest(
      `Model file exceeds limit of ${maxBytes} bytes`,
      "repository_url",
    );
  }
  if (!res.body) throw conflict("Download failed: empty response body", "repository_url");

  const target = modelFile(layout, modelId);
  await Deno.mkdir(modelDir(layout, modelId), { recursive: true });
  const tmp = `${target}.part-${crypto.randomUUID()}`;
  let file: Deno.FsFile | null = null;
  try {
    file = await Deno.open(tmp, { write: true, create: true, truncate: true });
    let total = 0;
    const reader = res.body.getReader();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      if (value) {
        total += value.byteLength;
        if (maxBytes > 0 && total > maxBytes) {
          await reader.cancel().catch(() => {});
          throw badRequest(
            `Model file exceeds limit of ${maxBytes} bytes`,
            "repository_url",
          );
        }
        await file.write(value);
      }
    }
    await file.close();
    file = null;
    await Deno.rename(tmp, target);
    const fileHash = await sha256File(target);
    return { fileHash, fileBytes: total };
  } finally {
    if (file) {
      try {
        await file.close();
      } catch {
        // already closed
      }
    }
    await Deno.remove(tmp, { recursive: false }).catch(() => {});
  }
}

/**
 * Full install flow for a model row — the install route and the model-copilot
 * `install_model` tool share this. Network sources require explicit consent
 * (MOD-013); optional overrides let the route pass request-body values.
 */
export async function installModelById(
  modelId: string,
  opts: { consent?: boolean; sourcePath?: string; repositoryUrl?: string } = {},
): Promise<{ model: Model; install: InstallResult }> {
  const model = getModel(modelId);
  if (!model) throw notFound("Model not found");

  const sourcePath = opts.sourcePath ?? model.source_path ?? undefined;
  const repositoryUrl = opts.repositoryUrl ?? model.repository_url ?? undefined;
  const lay = storageLayout(loadConfig().appDataDir);
  let result: InstallResult;
  if (sourcePath) {
    result = await installFromLocal(lay, modelId, sourcePath);
  } else if (repositoryUrl) {
    if (opts.consent !== true) {
      throw badRequest(
        "Installing from a network source requires explicit consent (consent: true)",
        "consent",
      );
    }
    result = await installFromUrl(lay, modelId, repositoryUrl, loadConfig().modelDownloadMaxBytes);
  } else if (model.source === "mock" || model.backend === "mock") {
    result = { fileHash: model.file_hash ?? "", fileBytes: 0 };
  } else {
    throw badRequest(
      "No installation source: provide source_path or repository_url on the model",
    );
  }

  const installed = setModelInstalled(modelId, result.fileHash);
  if (!installed) throw notFound("Model not found");
  return { model: installed, install: result };
}

/** Remove installed files for a model (MOD-005). */
export async function removeModelFiles(
  layout: StorageLayout,
  modelId: string,
): Promise<boolean> {
  const dir = modelDir(layout, modelId);
  try {
    const stat = await Deno.stat(dir);
    if (!stat.isDirectory) return false;
  } catch {
    return false;
  }
  await Deno.remove(dir, { recursive: true });
  return true;
}

export interface VerifyResult {
  valid: boolean;
  fileHash: string;
  expectedHash: string | null;
  message: string;
}

/** Checksum validation (MOD-004). */
export async function verifyModelFile(
  layout: StorageLayout,
  modelId: string,
  expectedHash: string | null,
): Promise<VerifyResult> {
  const file = modelFile(layout, modelId);
  if (!(await fileExists(file))) {
    return {
      valid: false,
      fileHash: "",
      expectedHash,
      message: "Model file not found (model not installed?)",
    };
  }
  const fileHash = await sha256File(file);
  if (expectedHash === null || expectedHash === "") {
    return {
      valid: true,
      fileHash,
      expectedHash,
      message: "No stored hash; recorded current hash",
    };
  }
  const valid = fileHash === expectedHash;
  return {
    valid,
    fileHash,
    expectedHash,
    message: valid ? "Checksum matches" : "Checksum mismatch: file does not match stored hash",
  };
}
